GET http://localhost:3333/random-between/5/10
###
GET http://localhost:3333/saveRecipe/burger%20vegan%20aux%20haricots%20rouges/https://www.marmiton.org/recettes/recette_burger-vegan-aux-haricots-rouges_345404.aspx/27%20minutes/3.8:5

###
GET http://localhost:3333/saveRecipe/crepes/image.jpg/2/4